//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixtyNineDegrees.MiteDesk.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixtyNineDegrees.MiteDesk.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Connected {
            get {
                object obj = ResourceManager.GetObject("Connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disconnected {
            get {
                object obj = ResourceManager.GetObject("Disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap faviconico {
            get {
                object obj = ResourceManager.GetObject("faviconico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hilfe {
            get {
                object obj = ResourceManager.GetObject("hilfe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Locked {
            get {
                object obj = ResourceManager.GetObject("Locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loginhelp {
            get {
                object obj = ResourceManager.GetObject("loginhelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_clock_animated_15x15 {
            get {
                object obj = ResourceManager.GetObject("mini_clock_animated_15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_1 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_2 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_3 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_4 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_5 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_6 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_7 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mite_desk_icon_16x16_8 {
            get {
                object obj = ResourceManager.GetObject("mite_desk_icon_16x16_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_1 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_2 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_3 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_4 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_5 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_6 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_7 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon mitedesk_clock_8 {
            get {
                object obj = ResourceManager.GetObject("mitedesk_clock_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
