//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixtyNineDegrees.MiteDesk.WinForms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixtyNineDegrees.MiteDesk.WinForms.Localization.MainLabels", typeof(MainLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Stoppuhr angehalten werden?.
        /// </summary>
        internal static string AskForStoppingStopwatch {
            get {
                return ResourceManager.GetString("AskForStoppingStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbunden als.
        /// </summary>
        internal static string AuthenticatedAs {
            get {
                return ResourceManager.GetString("AuthenticatedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung herstellen.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbunden.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zu mite. fehlgeschlagen.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung trennen.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht verbunden.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender.
        /// </summary>
        internal static string GroupboxCalendarTitle {
            get {
                return ResourceManager.GetString("GroupboxCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Zeiteintrag erstellen.
        /// </summary>
        internal static string GroupboxFormCreateMode {
            get {
                return ResourceManager.GetString("GroupboxFormCreateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeiteintrag bearbeiten.
        /// </summary>
        internal static string GroupboxFormEditMode {
            get {
                return ResourceManager.GetString("GroupboxFormEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge für den.
        /// </summary>
        internal static string GroupboxTimeEntriesTitle {
            get {
                return ResourceManager.GetString("GroupboxTimeEntriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leistung.
        /// </summary>
        internal static string LabelActivity {
            get {
                return ResourceManager.GetString("LabelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewählte Kalenderwoche:.
        /// </summary>
        internal static string LabelCalendarWeek {
            get {
                return ResourceManager.GetString("LabelCalendarWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        internal static string LabelDuration {
            get {
                return ResourceManager.GetString("LabelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        internal static string LabelNote {
            get {
                return ResourceManager.GetString("LabelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        internal static string LabelProject {
            get {
                return ResourceManager.GetString("LabelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossen.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als abgeschlossen markieren.
        /// </summary>
        internal static string MarkAsLocked {
            get {
                return ResourceManager.GetString("MarkAsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als nicht-abgeschlossen markieren.
        /// </summary>
        internal static string MarkAsUnlocked {
            get {
                return ResourceManager.GetString("MarkAsUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über mite.desk.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        internal static string MenuActivate {
            get {
                return ResourceManager.GetString("MenuActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leistungen.
        /// </summary>
        internal static string MenuActivities {
            get {
                return ResourceManager.GetString("MenuActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Updates prüfen.
        /// </summary>
        internal static string MenuCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden.
        /// </summary>
        internal static string MenuCustomers {
            get {
                return ResourceManager.GetString("MenuCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten.
        /// </summary>
        internal static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback senden.
        /// </summary>
        internal static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mite.account.
        /// </summary>
        internal static string MenuMiteAccount {
            get {
                return ResourceManager.GetString("MenuMiteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Zeiteintrag erstellen.
        /// </summary>
        internal static string MenuNewTimeEntry {
            get {
                return ResourceManager.GetString("MenuNewTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onlinehilfe.
        /// </summary>
        internal static string MenuOnlinehelp {
            get {
                return ResourceManager.GetString("MenuOnlinehelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte.
        /// </summary>
        internal static string MenuProjects {
            get {
                return ResourceManager.GetString("MenuProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte/Leistungen neu laden.
        /// </summary>
        internal static string MenuRefreshProjectsAndActivities {
            get {
                return ResourceManager.GetString("MenuRefreshProjectsAndActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mite.desk-Website.
        /// </summary>
        internal static string MenuWebsite {
            get {
                return ResourceManager.GetString("MenuWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zu mite. konnte nicht hergestellt werden.
        /// </summary>
        internal static string MsgBoxConnectionErrorText {
            get {
                return ResourceManager.GetString("MsgBoxConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsfehler.
        /// </summary>
        internal static string MsgBoxConnectionErrorTitle {
            get {
                return ResourceManager.GetString("MsgBoxConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du diesen Zeiteintrag wirklich löschen?.
        /// </summary>
        internal static string MsgBoxDeleteTimeEntryText {
            get {
                return ResourceManager.GetString("MsgBoxDeleteTimeEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string MsgBoxDeleteTimeEntryTitle {
            get {
                return ResourceManager.GetString("MsgBoxDeleteTimeEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string NotifyContextMenuExit {
            get {
                return ResourceManager.GetString("NotifyContextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        internal static string NotifyContextMenuRestoreWindow {
            get {
                return ResourceManager.GetString("NotifyContextMenuRestoreWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr starten.
        /// </summary>
        internal static string NotifyContextMenuStartStopwatch {
            get {
                return ResourceManager.GetString("NotifyContextMenuStartStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr anhalten.
        /// </summary>
        internal static string NotifyContextMenuStopStopwatch {
            get {
                return ResourceManager.GetString("NotifyContextMenuStopStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr starten.
        /// </summary>
        internal static string StartStopwatch {
            get {
                return ResourceManager.GetString("StartStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr anhalten.
        /// </summary>
        internal static string StopStopwatch {
            get {
                return ResourceManager.GetString("StopStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr.
        /// </summary>
        internal static string Stopwatch {
            get {
                return ResourceManager.GetString("Stopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoppuhr nicht gestartet.
        /// </summary>
        internal static string StopwatchNotStarted {
            get {
                return ResourceManager.GetString("StopwatchNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit gesamt:.
        /// </summary>
        internal static string TimeTotal {
            get {
                return ResourceManager.GetString("TimeTotal", resourceCulture);
            }
        }
    }
}
