//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixtyNineDegrees.MiteDesk.WinForms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixtyNineDegrees.MiteDesk.WinForms.Localization.SettingsLabels", typeof(SettingsLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountGroupboxTitle {
            get {
                return ResourceManager.GetString("AccountGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string AccountLabelAccountName {
            get {
                return ResourceManager.GetString("AccountLabelAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlüssel.
        /// </summary>
        internal static string AccountLabelAPIKey {
            get {
                return ResourceManager.GetString("AccountLabelAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden via.
        /// </summary>
        internal static string AccountLabelConnectBy {
            get {
                return ResourceManager.GetString("AccountLabelConnectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Schlüssel.
        /// </summary>
        internal static string AccountLabelConnectByApiKey {
            get {
                return ResourceManager.GetString("AccountLabelConnectByApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail/Passwort.
        /// </summary>
        internal static string AccountLabelConnectByEmailAndPassword {
            get {
                return ResourceManager.GetString("AccountLabelConnectByEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string AdvancedGroupboxTitle {
            get {
                return ResourceManager.GetString("AdvancedGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mite.desk beim Schließen des Fensters nicht beenden, sondern minimieren.
        /// </summary>
        internal static string AdvancedLabelMinimizeByClose {
            get {
                return ResourceManager.GetString("AdvancedLabelMinimizeByClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vor dem Beenden fragen, ob die Stoppuhr angehalten werden soll.
        /// </summary>
        internal static string AskForStoppingStopwatchByClosing {
            get {
                return ResourceManager.GetString("AskForStoppingStopwatchByClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung testen.
        /// </summary>
        internal static string ButtonCheckConnection {
            get {
                return ResourceManager.GetString("ButtonCheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string LanguageGroupboxTitle {
            get {
                return ResourceManager.GetString("LanguageGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung per E-Mail/Passwort.
        /// </summary>
        internal static string LoginByAccountGroupboxTitle {
            get {
                return ResourceManager.GetString("LoginByAccountGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse.
        /// </summary>
        internal static string LoginByAccountLabelEmail {
            get {
                return ResourceManager.GetString("LoginByAccountLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string LoginByAccountLabelPassword {
            get {
                return ResourceManager.GetString("LoginByAccountLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort anzeigen.
        /// </summary>
        internal static string LoginByAccountLabelShowPassword {
            get {
                return ResourceManager.GetString("LoginByAccountLabelShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung per API-Schlüssel.
        /// </summary>
        internal static string LoginByApiKeyGroupboxTitle {
            get {
                return ResourceManager.GetString("LoginByApiKeyGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: {0}
        ///
        ///Hast du den Zugriff auf die mite.api in deinem Account aktiviert?.
        /// </summary>
        internal static string MsgBoxConnectionTestFailureText {
            get {
                return ResourceManager.GetString("MsgBoxConnectionTestFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zu mite. fehlgeschlagen..
        /// </summary>
        internal static string MsgBoxConnectionTestFailureTitle {
            get {
                return ResourceManager.GetString("MsgBoxConnectionTestFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung erfolgreich. Angemeldet als: {0} ({1}).
        /// </summary>
        internal static string MsgBoxConnectionTestSuccessText {
            get {
                return ResourceManager.GetString("MsgBoxConnectionTestSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung erfolgreich hergestellt.
        /// </summary>
        internal static string MsgBoxConnectionTestSuccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxConnectionTestSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib zunächst deine mite.-Zugangsdaten oder deinen persönlichen API-Schlüssel ein.
        ///
        ///(Beachte auch, dass zum Zugriff die mite.api für deinen Account aktiviert sein muss.).
        /// </summary>
        internal static string MsgBoxFirstSetupMessageText {
            get {
                return ResourceManager.GetString("MsgBoxFirstSetupMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen bei mite.desk!.
        /// </summary>
        internal static string MsgBoxFirstSetupMessageTitle {
            get {
                return ResourceManager.GetString("MsgBoxFirstSetupMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-Server.
        /// </summary>
        internal static string ProxyServer {
            get {
                return ResourceManager.GetString("ProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy-Server verwenden.
        /// </summary>
        internal static string ProxyServerLabel {
            get {
                return ResourceManager.GetString("ProxyServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        internal static string ProxyUser {
            get {
                return ResourceManager.GetString("ProxyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichere Verbindung mit SSL-Verschlüsselung verwenden.
        /// </summary>
        internal static string SecurityConnectBySSL {
            get {
                return ResourceManager.GetString("SecurityConnectBySSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheit.
        /// </summary>
        internal static string SecurityGroupboxTitle {
            get {
                return ResourceManager.GetString("SecurityGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge in umgekehrter Reihenfolge sortieren (neueste zuerst).
        /// </summary>
        internal static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartGroupboxTitle {
            get {
                return ResourceManager.GetString("StartGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mite.desk bei der Windows-Anmeldung automatisch starten (Autostart).
        /// </summary>
        internal static string StartLabelAutostart {
            get {
                return ResourceManager.GetString("StartLabelAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimiert starten.
        /// </summary>
        internal static string StartLabelStartMinimized {
            get {
                return ResourceManager.GetString("StartLabelStartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Beenden die Stoppuhr automatisch anhalten.
        /// </summary>
        internal static string StopStopwatchByClosing {
            get {
                return ResourceManager.GetString("StopStopwatchByClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string TabAccount {
            get {
                return ResourceManager.GetString("TabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erweitert.
        /// </summary>
        internal static string TabAdvanced {
            get {
                return ResourceManager.GetString("TabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string TabLanguage {
            get {
                return ResourceManager.GetString("TabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerk.
        /// </summary>
        internal static string TabNetwork {
            get {
                return ResourceManager.GetString("TabNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string TabUpdates {
            get {
                return ResourceManager.GetString("TabUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeiteinträge.
        /// </summary>
        internal static string TimeEntriesGroupboxTitle {
            get {
                return ResourceManager.GetString("TimeEntriesGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemals.
        /// </summary>
        internal static string UpdateCheck0 {
            get {
                return ResourceManager.GetString("UpdateCheck0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 14 Tage.
        /// </summary>
        internal static string UpdateCheck14 {
            get {
                return ResourceManager.GetString("UpdateCheck14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 30 Tage.
        /// </summary>
        internal static string UpdateCheck30 {
            get {
                return ResourceManager.GetString("UpdateCheck30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 7 Tage.
        /// </summary>
        internal static string UpdateCheck7 {
            get {
                return ResourceManager.GetString("UpdateCheck7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie.
        /// </summary>
        internal static string UpdateCheckNever {
            get {
                return ResourceManager.GetString("UpdateCheckNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Update-Prüfung.
        /// </summary>
        internal static string UpdatesGroupboxTitle {
            get {
                return ResourceManager.GetString("UpdatesGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Updates prüfen.
        /// </summary>
        internal static string UpdatesLabelInterval {
            get {
                return ResourceManager.GetString("UpdatesLabelInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt geprüft.
        /// </summary>
        internal static string UpdatesLabelLastUpdatecheck {
            get {
                return ResourceManager.GetString("UpdatesLabelLastUpdatecheck", resourceCulture);
            }
        }
    }
}
